In [2]:
with open('SMSSpamCollection.txt','r') as file:
      data = file.read()  

In [3]:
len(data)   #total emails

477907

In [4]:

data[1]    

'a'

In [5]:
email_ls = data.split('\n')


In [71]:
y

2398     ham
1401     ham
503      ham
1763     ham
87       ham
        ... 
5539    spam
5542    spam
5549    spam
5568    spam
5569    spam
Name: label, Length: 1747, dtype: object

In [72]:
x = []
y = []
for line in email_ls:
    email_with_labels = line.split('\t')
    if len(email_with_labels) == 2:
        x.append(email_with_labels[1])
        y.append(email_with_labels[0])

In [73]:
len(x), len(y)

(5574, 5574)

In [74]:
x[10]

"I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."

In [75]:
y[10]

'ham'

In [76]:
import re  #model trainer

In [80]:
for i in range(len(x)):
    x[i] = re.sub('[^a-zA-Z ]',' ',x[i]).lower()

In [81]:
x[21]

'i   m going to try for   months ha ha only joking'

In [82]:
import pandas as pd 
dt = {"email_message":x,"label":y}
df = pd.DataFrame(dt)
df.head()

email_message label
0  go until jurong point  crazy   available only ...   ham
1                      ok lar    joking wif u oni      ham
2  free entry in   a wkly comp to win fa cup fina...  spam
3  u dun say so early hor    u c already then say      ham
4  nah i don t think he goes to usf  he lives aro...   ham

In [83]:
df['label'].value_counts()    

ham     4827
spam     747
Name: label, dtype: int64

In [84]:
ham = df[df['label']=='ham']
spam = df[df['label']=='spam']

In [85]:
ham.shape  ,  spam.shape

((4827, 2), (747, 2))

In [86]:
ham.sample(1000).shape

(1000, 2)

In [87]:
!pip install imblearn

In [88]:
from imblearn.over_sampling import SMOTE

In [89]:
smote = SMOTE()

In [92]:
ham = ham.sample(1000)    #randomly selecting 1000 dataframes 

In [93]:
balance_df = pd.concat([ham,spam])

In [94]:
balance_df['label'].value_counts()

ham     1000
spam     747
Name: label, dtype: int64

In [95]:
x = balance_df['email_message']
y = balance_df['label']

In [96]:
x = x.values
type(x)

numpy.ndarray

In [97]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
bow = CountVectorizer(max_features=1700, stop_words='english')  

In [99]:
x = bow.fit_transform(x).toarray()

In [101]:
x.shape

(1747, 1700)

In [104]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [107]:
column_name = bow.get_feature_names_out()

In [108]:
testing = pd.DataFrame(x, columns=column_name)

In [109]:
df.iloc[1]

email_message    ok lar    joking wif u oni   
label                                      ham
Name: 1, dtype: object

In [110]:
y

2595     ham
2741     ham
3106     ham
4737     ham
69       ham
        ... 
5539    spam
5542    spam
5549    spam
5568    spam
5569    spam
Name: label, Length: 1747, dtype: object

In [111]:

dt = {'ham':0,'spam':1}
y=y.map(dt)

In [112]:
dt

{'ham': 0, 'spam': 1}

In [113]:
import numpy as np

In [114]:
y = np.array(y)

In [115]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [116]:
x.shape, y.shape

((1747, 1700), (1747,))

In [117]:
from sklearn.model_selection import train_test_split

In [118]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.15)

In [119]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB

In [123]:
mb = MultinomialNB()
bnb = BernoulliNB()

mb.fit(x_train, y_train)
bnb.fit(x_train,y_train)

print("Training score MNB: ",mb.score(x_train,y_train))
print("Testing score MNB: ",mb.score(x_test,y_test))
print()
print("Training score BNB: ",bnb.score(x_train,y_train))
print("Testing score BNB: ",bnb.score(x_test,y_test))

Training score MNB:  0.9743935309973046
Testing score MNB:  0.9581749049429658

Training score BNB:  0.9663072776280324
Testing score BNB:  0.9543726235741445


In [124]:
import joblib

In [125]:
joblib.dump(bnb, 'BNB_Model.lb')
joblib.dump(bow, 'countvectorizer.lb')

['countvectorizer.lb']

In [127]:
prediction = bnb.predict(x_test)

In [128]:
prediction[:10]

array([0, 1, 1, 0, 0, 1, 0, 0, 1, 1], dtype=int64)

In [130]:
y_test[:10]

array([0, 1, 1, 0, 0, 1, 0, 0, 1, 1], dtype=int64)